import './styles/main.scss';
import {} from 'bootstrap';
import Logo from './assets/icons/logo.svg';
import Slack from './assets/icons/logo-slack.svg';
import Netflix from './assets/icons/logo-netflix.svg';
import Google from './assets/icons/logo-google.svg';
import Airbnb from './assets/icons/logo-airbnb.svg';
import Uber from './assets/icons/logo-uber.svg';
import Computer from './assets/icons/icon-computer.svg';
import Home from './assets/icons/icon-home.svg';
import Message from './assets/icons/icon-message.svg';
import Arrow from './assets/icons/arrow-right.svg';
import Mac from './assets/icons/logo-apple.svg';
import Windows from './assets/icons/logo-windows.svg';
import Linux from './assets/icons/logo-linux.svg';
import Heart from './assets/icons/icon-heart.svg';
import GoogleSmall from './assets/icons/logo-google-small.svg';
import Twitter from './assets/icons/logo-twitter.svg';
import Instagram from './assets/icons/logo-instagram.svg';
import LiknedIN from './assets/icons/logo-linkedin.svg';
import Shopify from './assets/icons/logo-shopify.svg';
import SlackSmall from './assets/icons/logo-slack-small.svg';
import Jira from './assets/icons/logo-jira.svg';
import DigitalOcean from './assets/icons/logo-digialoceaon.svg';
import Analytics from './assets/icons/logo-analytics.svg';
import Dropbox from './assets/icons/logo-dropbox.svg';
import Trello from './assets/icons/logo-trello.svg';
import Drive from './assets/icons/logo-drive.svg';
import Github from './assets/icons/logo-github.svg';
import Asana from './assets/icons/logo-asana.svg';
import Notion from './assets/icons/logo-notion.svg';
import Chevron from './assets/icons/icon-chevron-right.svg';
import ChevronLeft from './assets/icons/chevron-left.svg';
import Toggle from './assets/icons/Toggle.svg';
const WebLogo = document.getElementById('logo');
const logoFooter = document.getElementById('logoFooter');
const SlackLogo = document.getElementById('slack');
const NetflixLogo = document.getElementById('netflix');
const GoogleLogo = document.getElementById('google');
const AirbnbLogo = document.getElementById('airbnb');
const UberLogo = document.getElementById('uber');
const ComputerLogo = document.getElementById('computer');
const HomeLogo = document.getElementById('home');
const MessageLogo = document.getElementById('message');
const ArrowLogo = document.getElementById('arrow');
const MacLogo = document.getElementById('mac');
const WindowsLogo = document.getElementById('windows');
const LinuxLogo = document.getElementById('linux');
const HeartLogo = document.getElementById('heart');
const GoogleSmallLogo = document.getElementById('googleSmall');
const TwitterLogo = document.getElementById('twitter');
const InstagramLogo = document.getElementById('instagram');
const LinkedInLogo = document.getElementById('linkedin');
const ShopifyLogo = document.getElementById('shopify');
const SlackSmallLogo = document.getElementById('slackSmall');
const JiraLogo = document.getElementById('jira');
const DigitalOceanLogo = document.getElementById('digitalOcean');
const AnalyticsLogo = document.getElementById('analytics');
const DropboxLogo = document.getElementById('dropbox');
const TrelloLogo = document.getElementById('trello');
const DriveLogo = document.getElementById('drive');
const GithubLogo = document.getElementById('github');
const AsanaLogo = document.getElementById('asana');
const NotionLogo = document.getElementById('notion');
const ChevronLogo = document.getElementById('chevron');
const ChevronLeftLogo = document.getElementById('chevronleft');
const ToggleLogo = document.getElementById('toggle');
WebLogo.src = Logo;
logoFooter.src = Logo;
SlackLogo.src = Slack;
NetflixLogo.src = Netflix;
GoogleLogo.src = Google;
AirbnbLogo.src = Airbnb;
UberLogo.src = Uber;
ComputerLogo.src = Computer;
HomeLogo.src = Home;
MessageLogo.src = Message;
ArrowLogo.src = Arrow;
MacLogo.src = Mac;
WindowsLogo.src = Windows;
LinuxLogo.src = Linux;
HeartLogo.src = Heart;
GoogleSmallLogo.src = GoogleSmall;
TwitterLogo.src = Twitter;
InstagramLogo.src = Instagram;
LinkedInLogo.src = LiknedIN;
ShopifyLogo.src = Shopify;
SlackSmallLogo.src = SlackSmall;
JiraLogo.src = Jira;
DigitalOceanLogo.src = DigitalOcean;
AnalyticsLogo.src = Analytics;
DropboxLogo.src = Dropbox;
TrelloLogo.src = Trello;
DriveLogo.src = Drive;
GithubLogo.src = Github;
AsanaLogo.src = Asana;
NotionLogo.src = Notion;
ChevronLogo.src = Chevron;
ChevronLeftLogo.src = ChevronLeft;
ToggleLogo.src = Toggle;
